export const EXPECTED_ACTIVE_WORKFLOW_STATES = [
  "CargaVendedor|VENDEDORES",
  "Confirmada|RIESGO",
  "Desestimada|HISTORIAL",
  "Liquidada|VENDEDORES",
  "Motor|SISTEMA",
  "Pagada|HISTORIAL",
  "PreAprobada|VENDEDORES",
  "Rechazada|HISTORIAL",
  "Revisar|VENDEDORES",
  "RevisionRiesgo|RIESGO",
  "Transferir|TESORERIA",
  "Vencida|HISTORIAL",
  "VerificarFirmaYDocumentacion|RIESGO",
] as const;

export const EXPECTED_ACTIVE_WORKFLOW_TRANSITIONS = [
  "CargaVendedor|desestimar|Desestimada",
  "CargaVendedor|enviar|Motor",
  "CargaVendedor|vencer|Vencida",
  "Confirmada|desestimar|Desestimada",
  "Confirmada|liquidar|Liquidada",
  "Liquidada|desestimar|Desestimada",
  "Liquidada|verificar_firma|VerificarFirmaYDocumentacion",
  "Motor|motor|RevisionRiesgo",
  "PreAprobada|confirmar|Confirmada",
  "PreAprobada|desestimar|Desestimada",
  "PreAprobada|revisar_monto_cuota|RevisionRiesgo",
  "Revisar|desestimar|Desestimada",
  "Revisar|revisar_reenviar|RevisionRiesgo",
  "RevisionRiesgo|confirmar|Confirmada",
  "RevisionRiesgo|preaprobar|PreAprobada",
  "RevisionRiesgo|rechazar|Rechazada",
  "RevisionRiesgo|revisar|Revisar",
  "Transferir|pagar|Pagada",
  "VerificarFirmaYDocumentacion|devolver_a_liquidada|Liquidada",
  "VerificarFirmaYDocumentacion|transferir|Transferir",
] as const;

export const LEGACY_WORKFLOW_STATE_CODES = [
  "Abandonada",
  "ParaTransferir",
  "PreAprobado",
  "VerificacionFirmas",
  "VerificacionRiesgo",
] as const;

export const EXPECTED_WORKFLOW_BOOTSTRAP_METADATA = {
  "CargaVendedor|desestimar|Desestimada": {
    actionLabel: "Desestimar",
    defaultComment: "Desestimar",
    description: null,
    requiresComment: true,
    sortOrder: 30,
  },
  "CargaVendedor|enviar|Motor": {
    actionLabel: "Enviar",
    defaultComment: "Revisión de riesgo",
    description: null,
    requiresComment: false,
    sortOrder: 10,
  },
  "CargaVendedor|vencer|Vencida": {
    actionLabel: "Vencida",
    defaultComment: null,
    description: null,
    requiresComment: false,
    sortOrder: 20,
  },
  "Confirmada|desestimar|Desestimada": {
    actionLabel: "Desestimar",
    defaultComment: "Desestimar",
    description: null,
    requiresComment: true,
    sortOrder: 10,
  },
  "Confirmada|liquidar|Liquidada": {
    actionLabel: "Liquidada",
    defaultComment: "Liquidada",
    description: null,
    requiresComment: false,
    sortOrder: 20,
  },
  "Liquidada|desestimar|Desestimada": {
    actionLabel: "Desestimar",
    defaultComment: "Desestimar",
    description: null,
    requiresComment: true,
    sortOrder: 10,
  },
  "Liquidada|verificar_firma|VerificarFirmaYDocumentacion": {
    actionLabel: "Verificar Firma y Documentación",
    defaultComment: "Verificar firma y documentación",
    description: null,
    requiresComment: true,
    sortOrder: 30,
  },
  "Motor|motor|RevisionRiesgo": {
    actionLabel: "Motor",
    defaultComment: "Revisión de riesgo",
    description: null,
    requiresComment: false,
    sortOrder: 10,
  },
  "PreAprobada|confirmar|Confirmada": {
    actionLabel: "Confirmar",
    defaultComment: "Confirmada",
    description: null,
    requiresComment: false,
    sortOrder: 30,
  },
  "PreAprobada|desestimar|Desestimada": {
    actionLabel: "Desestimar",
    defaultComment: "Negativa del cliente",
    description: null,
    requiresComment: true,
    sortOrder: 10,
  },
  "PreAprobada|revisar_monto_cuota|RevisionRiesgo": {
    actionLabel: "Revisar si es posible brindar un monto o cuota distinta",
    defaultComment: "Revisar si es posible brindar un monto o cuota distinta",
    description: null,
    requiresComment: true,
    sortOrder: 20,
  },
  "Revisar|desestimar|Desestimada": {
    actionLabel: "Desestimar",
    defaultComment: "Desestimar",
    description: null,
    requiresComment: true,
    sortOrder: 20,
  },
  "Revisar|revisar_reenviar|RevisionRiesgo": {
    actionLabel: "Revisar/Reenviar",
    defaultComment: "Devolver a Riesgo",
    description: null,
    requiresComment: true,
    sortOrder: 10,
  },
  "RevisionRiesgo|confirmar|Confirmada": {
    actionLabel: "Confirmar",
    defaultComment: "Confirmación directa",
    description: null,
    requiresComment: false,
    sortOrder: 40,
  },
  "RevisionRiesgo|preaprobar|PreAprobada": {
    actionLabel: "PreAprobada",
    defaultComment: "Preaprobada",
    description: null,
    requiresComment: false,
    sortOrder: 30,
  },
  "RevisionRiesgo|rechazar|Rechazada": {
    actionLabel: "Rechazada",
    defaultComment: null,
    description: null,
    requiresComment: true,
    sortOrder: 10,
  },
  "RevisionRiesgo|revisar|Revisar": {
    actionLabel: "Revisar",
    defaultComment: "Revisar documentación",
    description: null,
    requiresComment: true,
    sortOrder: 20,
  },
  "Transferir|pagar|Pagada": {
    actionLabel: "Pagada",
    defaultComment: null,
    description: null,
    requiresComment: false,
    sortOrder: 10,
  },
  "VerificarFirmaYDocumentacion|devolver_a_liquidada|Liquidada": {
    actionLabel: "Devolver a Liquidada",
    defaultComment: "La documentación presenta errores",
    description: null,
    requiresComment: true,
    sortOrder: 10,
  },
  "VerificarFirmaYDocumentacion|transferir|Transferir": {
    actionLabel: "Para Transferir",
    defaultComment: null,
    description: null,
    requiresComment: false,
    sortOrder: 20,
  },
} as const;
