<?php

return [
    'enabled' => filter_var(env('HERRAMIENTAS_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'branding' => [
        'eyebrow' => 'Asociacion Mutual Celesol',
        'title' => 'Herramientas Red Unisol',
        'headline' => 'Un acceso claro a automatizaciones y reportes operativos.',
        'description' => 'Unificamos en un solo lugar las herramientas que el equipo usa todos los dias, con una experiencia consistente, sobria y lista para crecer modulo por modulo.',
        'support_label' => 'Solicitar una nueva herramienta',
        'support_url' => 'https://wa.me/+5493516611746',
        'support_copy' => 'Cada nueva herramienta puede sumarse manualmente sin cambiar la identidad visual del hub.',
    ],
    'catalog' => [
        [
            'id' => 'consulta-renovacion-cruz-del-eje',
            'title' => 'Consulta Renovacion Cruz del Eje',
            'description' => 'Ingresa un CUIL y consulta si el socio puede renovar su prestamo, con respuesta directa del flujo de analisis de credito.',
            'category' => 'Analisis de credito',
            'status' => 'active',
            'icon' => 'credit-path',
            'actionLabel' => 'Consultar renovacion',
            'helper' => 'La consulta usa el webhook protegido de Kestra desde el backend Laravel.',
        ],
        [
            'id' => 'consulta-tope-descuento-caja',
            'title' => 'Consulta Tope Descuento Caja',
            'description' => 'Ingresa un CUIL y consulta el tope de descuento en Caja Jubilaciones.',
            'category' => 'Analisis de credito',
            'status' => 'active',
            'icon' => 'credit-path',
            'actionLabel' => 'Consultar caja',
            'helper' => 'La consulta usa el webhook protegido de Kestra desde el backend Laravel.',
        ],
        [
            'id' => 'consulta-quiebra-credix',
            'title' => 'Consulta CredixSA',
            'description' => 'Consulta CredixSA por CUIL, DNI y/o nombre para obtener coincidencias o el informe completo disponible.',
            'category' => 'Analisis de credito',
            'status' => 'active',
            'icon' => 'credit-path',
            'actionLabel' => 'Consultar CredixSA',
            'helper' => 'La consulta usa el webhook protegido de Kestra desde el backend Laravel.',
        ],
        [
            'id' => 'consulta-empleador',
            'title' => 'Consulta Datos de Empleador por CUIL o DNI',
            'description' => 'Ingresa un CUIL o DNI y consulta los datos de persona y empleador devueltos por el flujo de analisis de credito.',
            'category' => 'Analisis de credito',
            'status' => 'active',
            'icon' => 'credit-path',
            'actionLabel' => 'Consultar empleador',
            'helper' => 'Ingresa el CUIL o DNI y el backend Laravel consulta el webhook protegido de Kestra.',
        ],
        [
            'id' => 'consulta-cuad',
            'title' => 'Consulta CUAD Santa Fe',
            'description' => 'Ingresa un CUIL y consulta bruto, neto, cupo, afectado, disponible y deuda desde CUAD.',
            'category' => 'Analisis de credito',
            'status' => 'active',
            'icon' => 'credit-path',
            'actionLabel' => 'Consultar CUAD',
            'helper' => 'Ingresa el CUIL y el backend Laravel consulta el webhook protegido de Kestra.',
        ],
        [
            'id' => 'bcra-central-deudores',
            'title' => 'BCRA Central de Deudores PNFC',
            'description' => 'Abre el panel operativo para preparar la presentacion mensual BCRA, revisar reglas y descargar informacion.zip.',
            'category' => 'Regulatorio',
            'status' => 'active',
            'icon' => 'file-archive',
            'actionLabel' => 'Abrir panel',
            'helper' => 'El motor BCRA corre como servicio Python y conserva la logica regulatoria validada.',
            'openMode' => 'external',
        ],
    ],
    'bcra' => [
        'panel_url' => env('BCRA_PANEL_URL', 'http://127.0.0.1:8080'),
    ],
    'proxy' => [
        'consulta_renovacion_url' => env('ANALISIS_CREDITO_RENOVACION_WEBHOOK_URL'),
        'tope_descuento_caja_url' => env('ANALISIS_CREDITO_CONSULTA_CAJA'),
        'consulta_quiebra_credix_cache_url' => env('ANALISIS_CREDITO_QUIEBRA_CREDIX_CACHE_URL'),
        'consulta_quiebra_credix_url' => env('ANALISIS_CREDITO_QUIEBRA_CREDIX_WEBHOOK_URL'),
        'consulta_empleador_url' => env('ANALISIS_CREDITO_CONSULTA_EMPLEADOR_WEBHOOK_URL'),
        'consulta_cuad_url' => env('ANALISIS_CREDITO_CONSULTA_CUAD_WEBHOOK_URL'),
        'timeout_seconds' => (int) env('ANALISIS_CREDITO_TIMEOUT_SECONDS', 30),
        'cache_timeout_seconds' => (int) env('ANALISIS_CREDITO_CACHE_TIMEOUT_SECONDS', 3),
    ],
    'contabilidad' => [
        'path' => 'contabilidad/'.env('CONTABILIDAD_TRANSFER_PRIVATE_SLUG', '77q330j56z'),
        'output_root' => env('CONTABILIDAD_TRANSFER_OUTPUT_ROOT', '/data/contabilidad-transfer'),
    ],
    'objectives' => [
        'path' => 'objetivos/'.env('OBJECTIVES_DASHBOARD_PRIVATE_SLUG', 'oficina'),
        'snapshot_path' => env('OBJECTIVES_DASHBOARD_SNAPSHOT_PATH', storage_path('app/private/objetivos/latest.json')),
        'refresh_seconds' => (int) env('OBJECTIVES_DASHBOARD_REFRESH_SECONDS', 60),
    ],
];
