import type { MappedSocioRow } from "../../application/services/ClassifySocioMutualRow";
import {
  buildSocioColumnsSql,
  buildSocioRowValuesSql,
  escapeSqlString,
  sqlLiteral,
} from "./SocioSqlValues";

export { escapeSqlString, sqlLiteral };

const HEADER =
  "-- Auto-generated by scripts/pull-socios-vimax.ts\n" +
  "-- Seed of Socio rows pulled from Vimax F.Module.SocioMutual.\n" +
  "-- Do not edit by hand; re-run the script instead.\n\n";

const DEFAULT_ROWS_PER_STATEMENT = 500;

function buildInsertStatement(rows: MappedSocioRow[]): string {
  const valuesSql = rows.map(buildSocioRowValuesSql).join(",\n  ");

  return (
    `INSERT INTO "socios" (${buildSocioColumnsSql()})\n` +
    `VALUES\n  ${valuesSql}\n` +
    'ON CONFLICT ("cuit") DO NOTHING;\n'
  );
}

export function buildSociosSeedSql(
  rows: MappedSocioRow[],
  rowsPerStatement: number = DEFAULT_ROWS_PER_STATEMENT,
): string {
  const statements: string[] = [];

  for (let start = 0; start < rows.length; start += rowsPerStatement) {
    statements.push(buildInsertStatement(rows.slice(start, start + rowsPerStatement)));
  }

  return HEADER + statements.join("\n");
}
