import type { SolicitudAdjunto } from "../../domain/entities/SolicitudAdjunto.entity";

export const ownedSolicitud = (overrides?: Record<string, unknown>) => ({
  createdAt: new Date("2026-05-12T10:00:00.000Z"),
  createdBy: "user-1",
  cuotaResultante: "10000",
  cuotas: 12,
  ejecutivoSolicitud: "Ejecutivo Uno",
  estadoActual: {
    code: "CargaVendedor",
    id: "state-1",
    name: "Carga vendedor",
    ownerId: "owner-1",
  },
  firmaDigitalmente: false,
  id: "sol-1",
  garantias: [],
  legacyOid: null,
  lineaPrestamoDescripcion: "Personal",
  lineaPrestamoLegacyOid: "LP-1",
  montoAFinanciar: 100000,
  motivo: "Compra",
  nroSolicitud: null,
  observaciones: "Inicial",
  conyuge: null,
  datosLaborales: {
    actividadLaboral: null,
    antiguedadLaboralMeses: null,
    descuentosSueldo: null,
    domicilioLaboralCalle: null,
    domicilioLaboralLocalidad: null,
    domicilioLaboralNroPuerta: null,
    domicilioLaboralPisoDepto: null,
    empleador: null,
    fechaIngresoLaboral: null,
    montoRecibo: null,
    relacionLaboral: null,
    tarjetas: null,
    vehiculo: null,
    vivienda: null,
  },
  titular: {
    apellidoDenominacion: "Perez",
    cbu: null,
    celular: null,
    cuit: null,
    domicilioCalle: null,
    email: null,
    localidad: null,
    nombre: "Juan",
    nroDocumento: "33344455",
    nroPuerta: null,
    nroSocio: null,
    tipoDocumento: "DNI",
  },
  updatedAt: new Date("2026-05-12T10:00:00.000Z"),
  vendedorSolicitud: "Vendedor Uno",
  ...overrides,
});

export const storedAdjunto = (
  overrides?: Partial<SolicitudAdjunto>,
): SolicitudAdjunto => ({
  id: "adj-1",
  solicitudId: "sol-1",
  archivoNombre: "dni.pdf",
  archivoPath: "solicitudes/sol-1/adjuntos/dni.pdf",
  archivoMimeType: "application/pdf",
  archivoSizeBytes: 3,
  storageBucket: "solicitudes",
  tipoAdjunto: "DNI",
  estadoAdjunto: "Cargado",
  descripcion: "Documento nacional de identidad",
  adicional: "Frente",
  comentario: "DNI frente",
  nroDocumento: "33344455",
  restringido: true,
  uploadedBy: "user-1",
  uploadedAt: new Date("2026-05-12T10:00:00.000Z"),
  updatedAt: new Date("2026-05-12T10:00:00.000Z"),
  deletedAt: null,
  deletedBy: null,
  deleteReason: null,
  ...overrides,
});
